### ISSUE TITLE
kindle体验版浏览器打开空白，其它终端设备正常访问

### ISSUE THREAD

**Issue by jjss520** [uhziel/yireader#11]
不知道是我的kindle有问题还是怎么回事，kindle打开其它网址又有内容显示
郁闷了

**Comment by jjss520** [comment]
应该是kindle的浏览器是精简版，估计要专门适配，大佬看一看，为了KINDLE追小说试了各种方法，还有翻页能点击翻页吗？现在滑动看书太累了，水墨屏这样体验不好，希望作者能为kindle优化一下

**Comment by jjss520** [comment]
@uhziel

**Comment by uhziel** [comment]
#13

**Comment by jjss520** [comment]
> 下一步计划开发打包书并邮件发送到kindle，这种方式是不是可以解决你的问题了？

很少用邮箱推送，关键那种一天更新几章的，天天推送个文件也不方便，能解决KINDLE浏览器空白是最好的，没有其它人KINDLE浏览器空白？还是我是个个例？估计是kindle的浏览精简了个东西导致显示空白

**Comment by uhziel** [comment]
> 之前的 v0.2.1 版本用 kindle 浏览器能打开吗？
如果之前的版本能正常使用，我可以尝试处理下。

**Comment by jjss520** [comment]
> 如果之前的版本能正常使用，我可以尝试处理下。

我好像搭的最新的，没搭过0.2.1

**Comment by jjss520** [comment]
> > 之前的v0.2.1版本用kindle浏览器能打开吗？
> 
> 如果之前的版本能正常使用，我可以尝试处理下。

如果你这边有0.2.1版本的，我可以用kindle试试

**Comment by uhziel** [comment]
那应该是不行的。目前前端是Vuejs 单页面 web app，得现代浏览器才会支持。

后续，如果要支持 Kindle，得单独开发一个新前端，尽量用最基础的特性才行。

这个前端会只包含登录、登出加阅读的最基础功能，开发时间应该也还在控制范围。

**Comment by jjss520** [comment]
> 那应该是不行的。目前前端是Vuejs 单页面 web app，得现代浏览器才会支持。
> 
> 后续，如果要支持 Kindle，得单独开发一个新前端，尽量用最基础的特性才行。
> 
> 这个前端会只包含登录、登出加阅读的最基础功能，开发时间应该也还在控制范围。

kindle单独端可以域名:端口/kindle 这样来访问和正常的区分，其实kindle只要最简单的登陆保存阅读记录，然后还有最重要点击翻页就行了，还有一个问题就是字体的增加和减小可以弄在设置项里或者平时隐藏，点击时才会出来，这样不会影响阅读

**Comment by jjss520** [comment]
其实其它终端安卓ios阅读软件很成熟，就kindle在线追更是一大头痛，有的为了追更，更是把kindle刷成安卓，你可以加大力度来开发适配一下kindle可能使用群还能增加
