### ISSUE TITLE
g关于unraid部署

### ISSUE THREAD

**Issue by c999533** [uhziel/yireader#12]
你好，升级0.3版本后，docker按说明重新部署 过程都错误提示，但是docker里除了原来部署的yireader，还自动增加了yireader-db和yireader~yireader两个运行的程序，其中yireader~yireader因为端口问题没法启动，然后打开网页还是提示需要部署。请教一下是哪里的问题，谢谢！

**Comment by uhziel** [comment]
你这个从表现上看，是 yireader 没连上数据库 yireader-db。

请提供具体的错误提示内容，好辅助你进行分析。

**Comment by c999533** [comment]
at emitErrorNT (net.js:1345:8)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
code: 'EADDRINUSE',
errno: -98,
syscall: 'listen',
address: '::',
port: 3001
}
Please config your env MONGODB_URI first.
This process is pid 1
Listen on port 3001!
SIGTERM signal received: closing the application
yireader server closed
Monogodb connection closed
Please config your env MONGODB_URI first.
This process is pid 1
Listen on port 3001!
SIGTERM signal received: closing the application
yireader server closed
Monogodb connection closed
SIGTERM signal received: closing the application
yireader server closed
Monogodb connection closed
Please config your env MONGODB_URI first.
Please config your env MONGODB_URI first.
This process is pid 1
Listen on port 3001!

嗯，看了日记，应该是 config your env MONGODB_URI 这里的问题，但是找不到设置 哪里可以配置MONGODB_URI

**Comment by c999533** [comment]
可以了，之前旧版的设置不行，新版自动拉取的yireader_yireader启动，就可以用了。
