### ISSUE TITLE
如何登陆管理员账户？并关闭注册？

### ISSUE THREAD

**Issue by cjh1993129** [uhziel/yireader#16]
已经配置完成。
但如何登陆管理员账户？
私人自用，如何并关闭注册？
谢谢

**Comment by uhziel** [comment]
抱歉，目前并没有实现你说的功能。

如果确实很需要“关闭注册”，后续可以先临时加命令行环境变量的方式来控制。

**Comment by jacklaplace** [comment]
注册一个用户，使用一段时间，就习惯了
