### ISSUE TITLE
0.4版，ink版字体缩小最小还是感觉大了

### ISSUE THREAD

**Issue by jjss520** [uhziel/yireader#19]
能把字体再缩小点吗？
还有提个小小的意思，ink版或者普通版，能缓存章节吗？特别是ink版，比如缓存个50章，然后就可以把WIFI关了，一直开着非常耗电

**Comment by uhziel** [comment]
> 能把字体再缩小点吗？
这个我调整下。

> 还有提个小小的意思，ink版或者普通版，能缓存章节吗？特别是ink版，比如缓存个50章，然后就可以把WIFI关了，一直开着非常耗电
普通版其实是有缓存章节的，不过只是前后章节。这个后续等基础功能完善，可以再增强下。
ink版不大现实。Kindle 的浏览器太老，它的本地缓存实现存在问题，只要你离开浏览器再回来，本地缓存就会消失。

**Comment by jjss520** [comment]
ink版缓存，其实如果在看书的话，一直会在浏览器界面，很少去其实界面，除非换书
还有个小建议，INK版，点击翻页，为上下，左右翻页，左手不太方便

**Comment by uhziel** [comment]
> ink版缓存，其实如果在看书的话，一直会在浏览器界面，很少去其实界面，除非换书

个人感觉，离线阅读更好的方式是发送电子书到kindle，再在电子书末尾附上最新章节的链接。

> 还有个小建议，INK版，点击翻页，为上下，左右翻页，左手不太方便

没明白你的需求。目前是和微信读书一样，左1/3屏幕上一页，右2/3屏幕下一页。一般需求上一页的情况很少。你要觉得左手不方便，可以点击底部导航栏的`上一页`按钮。

**Comment by jjss520** [comment]
> > ink版缓存，其实如果在看书的话，一直会在浏览器界面，很少去其实界面，除非换书
> 
> 个人感觉，离线阅读更好的方式是发送电子书到kindle，再在电子书末尾附上最新章节的链接。
> 
> > 还有个小建议，INK版，点击翻页，为上下，左右翻页，左手不太方便
> 
> 没明白你的需求。目前是和微信读书一样，左1/3屏幕上一页，右2/3屏幕下一页。一般需求上一页的情况很少。你要觉得左手不方便，可以点击底部导航栏的`上一页`按钮。

kindle太大了，一个手看书太累，换到左手的时候单手手持，虽然2/3是下一页，但还是容易误触到上一页，所以希望改成屏幕上下翻页，这样解决了误解的问题，我现在只能右手手持，左手非常容易误触

**Comment by uhziel** [comment]
明白了，右手太累，换左手持握时的体验问题。这个下一版本处理下。

**Comment by jjss520** [comment]
> 明白了，右手太累，换左手持握时的体验问题。这个下一版本处理下。

字体别忘了改小

**Comment by uhziel** [comment]
已更新
