### ISSUE TITLE
[已解决]Portainer里映射的文件夹是什么？

### ISSUE THREAD

**Issue by jacklaplace** [uhziel/yireader#20]
请问，我用的镜像是普通版，portainer里要映射的文件夹是什么？我用/yireader映射到/nas/docker/yireader不行啊，用/yireader/dbdata映射到/nas/docker/yireader/dbdata也不行啊，路径是哪个？现在能运行和打开，就是部署不了。

有人要求字体小的，我要求字体大大大，可不可以从1~100自己输入字号啊？

最后，谢谢分享！

**Comment by jacklaplace** [comment]
/nas/docker里有文件夹yireader，yireader里有docker-compose.yml和文件夹dbdata

portainer里我把/volume1/docker映射到/nas/docker还是不行

**Comment by uhziel** [comment]
抱歉，我并没有使用过 portainer，无法给予直接的帮助。
不过你只需把本地任意目录，映射到易读docker镜像的`/data/db`目录即可。

调整字号这个，幸苦多点几次'放大'完成吧。现在得把精力花在基础功能完善上。

**Comment by jacklaplace** [comment]
/nas/文档/docker里有文件夹yireader，yireader里有docker-compose.yml和文件夹dbdata

是不是把/nas/文档/docker映射到/data/db就行了？

**Comment by jacklaplace** [comment]
把/nas/文档/docker映射到/data/db不行，还是显示要部署
把/nas/文档/docker/yireader映射到/data/db/yireader不行

**Comment by jacklaplace** [comment]
把/nas/文档/docker/yireader映射到/data/db不行
你的部署缺少数据库配置，请先按 部署 进行操作。


别的容器johnshine/baidunetdisk我把镜像介绍里写的下载目录/home/baidu/baidunetdiskdownload映射到/nas/文档/docker/baidunetdiskdownload就可以用了


到底哪里没弄对？

**Comment by jacklaplace** [comment]
已经解决了。谢谢作者的分享。

如果有使用portainer，而遇到困难的，可以留言，我也许可以给个参考。
