### ISSUE TITLE
字号和上下翻页都很好，感觉反映速度快了点，但有新问题

### ISSUE THREAD

**Issue by jjss520** [uhziel/yireader#21]
就是一页最后一行只显示一半，而点击翻页，从前一页最后一行没显示完成的，变成最上面，但也是显示一半，不知道是不是我字体设置小的原因

**Comment by jjss520** [comment]
断行，用了一下就好了，感觉点击翻页，不太灵敏，有时候要点两三下才行，能增加一下灵敏度吗

**Comment by uhziel** [comment]
翻页不灵敏是kindle自身导致的，这个不好解决。你用手机、电脑浏览器可以浏览下ink版，其实响应很快。

**Comment by jjss520** [comment]
> 翻页不灵敏是kindle自身导致的，这个不好解决。你用手机、电脑浏览器可以浏览下ink版，其实响应很快。

感觉是kindle浏览器本身的问题，直接看kindle里的本地书箱，反应还是很灵敏的，点击即翻页，浏览器，我一般要用大力点才会翻，感觉上就没那种一点即翻的感觉

**Comment by uhziel** [comment]
kindle浏览器本身就是一个实验浏览器，它的版本差不多就是十二年前的 pc 版 Safari 4，差一点还是能理解。
感觉最好的体验，还是把书打包成电子书发送到kindle本地阅读。后续的新更新，再用浏览器。
再就是，可以保持平和的心态可能会好点，轻按和大力按其实没差别。只要没点错地方，肯定是会翻页成功的。

**Comment by jjss520** [comment]
> kindle浏览器本身就是一个实验浏览器，它的版本差不多就是十二年前的 pc 版 Safari 4，差一点还是能理解。
> 感觉最好的体验，还是把书打包成电子书发送到kindle本地阅读。后续的新更新，再用浏览器。
> 再就是，可以保持平和的心态可能会好点，轻按和大力按其实没差别。只要没点错地方，肯定是会翻页成功的。

现在能用浏览器看更新，已经很好了，感谢你的修改。

**Comment by uhziel** [comment]
也感谢你很有价值的意见。
