### ISSUE TITLE
[已解决]改背景色：油猴“小说阅读脚本”添加ip:3001不生效

### ISSUE THREAD

**Issue by jacklaplace** [uhziel/yireader#22]
谷歌浏览器+油猴+小说阅读脚本，看小说不错
https://greasyfork.org/zh-CN/scripts/292-my-novel-reader

**现在想利用它里边的背景壁纸功能**
正常的话编辑脚本，添加一条小说网址就行，比如 

`*://www.xkzw.org/*/*.html`

那么，阅读这个网站的任何小说都可以启用这个小说模板了

现在添加一条 

`*://192.168.1.2:3001/*`

并不生效，请问要如何做呢？
**或者有什么其他浏览器或者工具可以自定义小说背景壁纸呢？**
最好是可以自定义 jpg 文件当背景图片

我找到其中一个方法：
怎么修改设置IE浏览器网页的背景色颜色为护眼色
https://jingyan.baidu.com/article/3c343ff7f08dad0d37796316.html

**Comment by jacklaplace** [comment]
已解决，方法是：
油猴+护眼脚本
https://greasyfork.org/zh-CN/scripts/14716-%E6%8A%A4%E7%9C%BC%E8%84%9A%E6%9C%AC


当然啦，最想要的还是能够自定义 jpg 背景图片，希望作者考虑考虑哦。

**Comment by uhziel** [comment]
嗯嗯先用浏览器插件达成你想要的效果吧。目前还得优先完成基础功能，需要做的事还挺多。
