### ISSUE TITLE
如何注册并登录？

### ISSUE THREAD

**Issue by Chengregnarok** [uhziel/yireader#23]
已经配置完成，注册时无法提交注册信息，已尝试IE、Edge、Chrome

**Comment by jacklaplace** [comment]
首先你是什么设备，其次你部署完成l吗？我用的portainer，先建立mongo容器，然后才建立yireader容器。

今天nas重启，ip+3001 用户登录不了，网页也不显示需要部署，进portainer发现是mongo没启动。然后我把mongo启动，也不行，想了一想再把yireader容器重启一次就好了。

综上，mongo必须先启动，然后再启动yireader，才可以注册和登录。

**Comment by jacklaplace** [comment]
除此之外，那就是你的yireader与mongo数据库之间配置不正确的问题了，他们两之间没有建立正确的连接。跟浏览器没关系。


你点击已关闭的 Issues，里边有别人分享的代码，按照试试看。
https://github.com/uhziel/yireader/issues/5

**Comment by Chengregnarok** [comment]
尝试几次重启容器确实解决了。感谢提醒
