### ISSUE TITLE
数据库如何配置

### ISSUE THREAD

**Issue by xudong198600** [uhziel/yireader#25]
我的群辉用docker安装完以后出现缺少数据库配置，具体需要怎么去配置数据库？我在说明文档里面也没有看到相关的配置。
![image](https://user-images.githubusercontent.com/54304722/126024415-a0d17319-2b8e-4ea8-b2e0-236fdde9f71c.png)

**Comment by uhziel** [comment]
文档是用 docker-compose 方式部署的，需要ssh登陆到你的群晖完成。

你目前这种手工部署的方法，可以参考 #5 #23 ，他们的情况可能对你有帮助。

**Comment by jacklaplace** [comment]
第一步，先部署docker 数据库，镜像名称叫“mongo:4.4-bionic”，并且把数据库使用的空间“/data/db”这个文件夹映射到你的群晖的本地文件夹。比如：

`端口映射 27017到27017
文件夹映射 /nas/文档/docker/yireader/dbdata 映射到 /data/db
参数：
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=88888888`
此时，数据库的地址就是 192.168.1.3:27017，下面要用到


第二步，才部署docker yireader，镜像名称叫“uhziel/yireader”，并且在环境里写入代码，用来指向存储的数据库。比如：

`端口映射 3001到3001
参数：
NODE_ENV=production
SECRET_KEY=88888888
MONGODB_URI=mongodb://root:88888888@192.168.1.3:27017/yireader?authSource=admin&retryWrites=true&w=majority`


最后，用浏览器打开 192.168.1.3:3001 就ok了。

**Comment by jacklaplace** [comment]
另外问一下作者，一本书，更新到30章，我添加到书架，点击目录，看第20章，yireader只会下载第20和第21章，其他的都不会下载，是这样吗？

接着上面，第二天我用另一台电脑直接调到第28章，此时，数据库里只有20、21、28、29章，其他都没有，是这样吗？

**Comment by uhziel** [comment]
是自动下载当前看的章节加上前一章节、后一章节。你这个情况最终会下载 19、20、21、27、28、29。

**Comment by jacklaplace** [comment]
那你的工作够多的

小说的目录不显示出哪些章节是已下载的，而且，保存下来的是残缺不全的，那数据库好像没什么意义，连记录流水都算不上，现在yireader纯纯是个界面干净的中转站。

如果你是一个人做这个，感觉是有生之年系列。。。

**Comment by xudong198600** [comment]
> mongo

你好，我怎么在docker上找不到mongo:4.4-bionic这个镜像名啊，能否告知一下搜索的关键字，谢谢。

**Comment by jacklaplace** [comment]
我看我的image里就是叫这个啊，复制粘贴的，mongo:4.4-bionic，448.9 MB，我之前研究时看作者的文档代码里写的全称就是这个，刚刚我去官网看了，没找到这个mongo:4.4-bionic，奇怪，难道撤包了？或者改名了？怎么还会对老版本的镜像改名呢？官网倒是看到一个叫 mongo:4.4和另一个叫 mongo:4.4-focal，你试试看。

我也没测试过用最新版mongo行不行，你可以测试下。我之前按技术文档怎么写就怎么做啦。

官网链接：`https://registry.hub.docker.com/_/mongo?tab=tags&page=1&ordering=last_updated`

**Comment by xudong198600** [comment]
> 我看我的image里就是叫这个啊，复制粘贴的，mongo:4.4-bionic，448.9 MB，我之前研究时看作者的文档代码里写的全称就是这个，刚刚我去官网看了，没找到这个mongo:4.4-bionic，奇怪，难道撤包了？或者改名了？怎么还会对老版本的镜像改名呢？官网倒是看到一个叫 mongo:4.4和另一个叫 mongo:4.4-focal，你试试看。
> 
> 我也没测试过用最新版mongo行不行，你可以测试下。我之前按技术文档怎么写就怎么做啦。
> 
> 官网链接：`https://registry.hub.docker.com/_/mongo?tab=tags&page=1&ordering=last_updated`

官网的很多版本我用群辉下载不下来，而且有些即使下载下来了无法运行，应该跟我的CPU架构有关系。我又招了一个可以下载可以安装的，镜像名叫“aashreys/mongo-auth”，按照要求进行配置后，打开页面点击注册没反应。这是什么一个原因？

**Comment by jacklaplace** [comment]
还显示要部署吗？如果还有部署两个字，那就是你没弄对，yireader没连接上数据库。

**Comment by xudong198600** [comment]
> 还显示要部署吗？如果还有部署两个字，那就是你没弄对，yireader没连接上数据库。

不显示了，只是没反应，mongo容器先启动的，后面在易读的容器里配置参数连接mongo容器的。

**Comment by jacklaplace** [comment]
我去查了一下这个 aashreys/mongo-auth，如下：

`# ENV MONGODB_ADMIN_USER root
# ENV MONGODB_ADMIN_PASS password

# ENV MONGODB_APPLICATION_DATABASE your_db
# ENV MONGODB_APPLICATION_USER user
# ENV MONGODB_APPLICATION_PASS password`

也就是说，它并不是像我用的那个mongo一样映射数据库路径的
我的是：A格式
/nas/文档/docker/yireader/dbdata 映射到 /data/db
它的是：B格式
`# ENV MONGODB_APPLICATION_DATABASE     /nas/文档/docker/yireader/dbdata`

你是用的A还是B格式？

**Comment by xudong198600** [comment]
> 我去查了一下这个 aashreys/mongo-auth，如下：
> 
> `ENV MONGODB_ADMIN_USER root`
> `ENV MONGODB_ADMIN_PASS password`
> 
> `ENV MONGODB_APPLICATION_DATABASE your_db`
> `ENV MONGODB_APPLICATION_USER user`
> `ENV MONGODB_APPLICATION_PASS password`
> 
> 也就是说，它并不是像我用的那个mongo一样映射数据库路径的
> 我的是：A格式
> /nas/文档/docker/yireader/dbdata 映射到 /data/db
> 它的是：B格式
> `ENV MONGODB_APPLICATION_DATABASE /nas/文档/docker/yireader/dbdata`
> 
> 你是用的A还是B格式？

应该用的是A格式，那意思是需要设置参数配置来设置数据库路径？

**Comment by jacklaplace** [comment]
对，按该镜像下面文档介绍的格式

**Comment by xudong198600** [comment]
> 对，按该镜像下面文档介绍的格式。因为不知道它打包的时候是不是用的和标准包一样的 /data/db 路径。
> 
> 而且你 MONGODB_APPLICATION_USER 都换了它的，路径咋不按它的呢？

好的，我试试，十分感谢！！

**Comment by xudong198600** [comment]
> > 对，按该镜像下面文档介绍的格式。因为不知道它打包的时候是不是用的和标准包一样的 /data/db 路径。
> > 而且你 MONGODB_APPLICATION_USER 都换了它的，路径咋不按它的呢？
> 
> 好的，我试试，十分感谢！！

终于搞定了，又重新下载的mongo官方的镜像，用的是mongo:rc这个版本的，现在已经可以成功连接。

**Comment by jacklaplace** [comment]
rc是什么版本，好像有很多个

**Comment by xudong198600** [comment]
> rc是什么版本，好像有很多个
> 
> 官网我又找到 4.4.0-bionic这个版本了，你在 filter tags 里输入一个小写字母 b，翻页就找到了
> 
> ebd31eaac273
> linux/amd64
> 169.73 MB
> 
> cd9b4445508d
> linux/arm64/v8
> 160.14 MB
> 
> f143bbac6c00
> linux/s390x
> 164.89 MB
> 
> **为什么我的image库里显示它有448.9 MB？**
> 
> **往下翻，还有一个叫 4.4-bionic，我惊呆了**
> 
> d9ddf3df3194
> linux/amd64
> 159.88 MB
> 
> aa3f99f22e19
> linux/arm64/v8
> 153 MB
> 
> 0373799eb994
> linux/s390x
> 161.64 MB

我的镜像就是rc版本，在tag里面有一个这个版本，可以使用。300多M
![image](https://user-images.githubusercontent.com/54304722/126745839-6bc94626-e18a-42a5-99ed-4f40557b65c0.png)

**Comment by jacklaplace** [comment]
找不到mongo:rc，算了，解决问题就行，你关闭话题吧。
