### ISSUE TITLE
群晖里docker教程不完整

### ISSUE THREAD

**Issue by yhj329335954** [uhziel/yireader#26]
在docker安装好，并固定好端口后进入页面，在显示的登录/注册界面上方，一直显示，“你的部署缺少数据库配置，请先按 部署 进行操作。”。。。群晖里docker“终端机”命令行很难用，而用ssh登录又没教程，求大佬指导

**Comment by chitaw** [comment]
用docker的界面操作很难，搜索下群晖的SSH教程，进入以后用docker-compose部署，就很容易
