### ISSUE TITLE
按照部署的方法部署，提示错误

### ISSUE THREAD

**Issue by zml9640** [uhziel/yireader#27]
很想用这个阅读器，但是装了几次都不行，不知道哪里问题，想用edge浏览器听书，不知道这个能不能实现，大佬可以建个群吗，我觉得这个阅读器搭配edge，简直神器

**Comment by uhziel** [comment]
你可以参考下 @jacklaplace  在 https://github.com/uhziel/yireader/issues/25#issuecomment-884122641 的说明。

讨论的话，可以在 https://github.com/uhziel/yireader/discussions 发帖子。

"edge浏览器听书"指的是什么？

**Comment by zml9640** [comment]
微软edge浏览器带的语音朗读功能

**Comment by zml9640** [comment]
![Uploading F2CCE6AD-DE1B-4060-985E-9CBBA60422FA.png…]()

**Comment by zml9640** [comment]
https://postimg.cc/kRFWpk5h

**Comment by uhziel** [comment]
你机器上的3001端口已经被占用，看是不是其他在跑的应用占用这个端口。

可以考虑把 docker-compose.yml 中的端口换成其他端口，比如 3002。

**Comment by zml9640** [comment]
部署好了，书源也能添加，搜索出来的书都不能阅读
![Uploading 355660BA-CC0E-41A6-A616-3F53E32BA19F.png…]()

**Comment by zml9640** [comment]
![CB1CA8FC-3CE4-44C6-94DE-4388ADC29D09](https://user-images.githubusercontent.com/67811948/130478625-d50d5748-dc76-4cc1-9967-02a89537bd3d.png)
![BB6C869C-43FB-48D7-8A25-10326D86CE9A](https://user-images.githubusercontent.com/67811948/130478636-629fbc41-d4f4-4926-92c4-eccad959c437.png)

**Comment by zml9640** [comment]
搜索出来的都不能阅读

**Comment by zml9640** [comment]
搜索出来的书阅读不了，能不能自己添加txt阅读

**Comment by zml9640** [comment]
https://postimg.cc/gnBSCxyL

**Comment by jacklaplace** [comment]
我就一个源，叫i笔趣阁，可以打开，你可以试试看

**Comment by zml9640** [comment]
试了，还是不行

**Comment by jacklaplace** [comment]
是任何小说都加载不出来吗？你等个2分钟看看啊，我的有时候打开也要等一等

**Comment by jacklaplace** [comment]
仙道第一小白脸，我试了，可以阅读第一章啊，其他章就不试了，你要截图的话留邮箱我发你看看。

**Comment by zml9640** [comment]
等两分钟可以了，原来要这样，这个i笔趣阁书源有水印，有没有不带水印的书源啊

**Comment by jacklaplace** [comment]
我试了五十多个源，懒得试了，你找到了告诉我一下
