### ISSUE TITLE
大佬辛苦了，docker里面可以考虑把易读的配置目录映射出来，这样以后docker重建也不会丢进度

### ISSUE THREAD

**Issue by db-one** [uhziel/yireader#5]
关注这个项目有一点时间了，大佬辛苦了，docker里面可以考虑把易读的配置目录映射出来，这样以后docker重建也不会丢进度
希望这样项目越做越完整，功能丰富起来

**Comment by uhziel** [comment]
非常感谢你提出宝贵的意见。
易读目前发布的版本我没有做配置功能，你说的配置目录指的是哪个？是 book_sources 那个目录吗？
目前我正在开发把数据都存放到数据库，等这样应该也不会丢数据了。

临时解决的话，可以试下这个方法：
在 docker 启动命令加上`-v <your_local_dir>:/app/book_sources`，<your_local_dir>是你电脑本地的绝对路径目录。

**Comment by db-one** [comment]
辛苦了

添加账号系统，方便用户跨设备间同步数据

相比这个，我觉得应该是直接保存到配置文件更简单方便，大家用这个的应该会做服务的很少吧，估计大多还是自己用，省去帐户系统可以快速更新其他功能，后期差不多了，想要帐户的可以再添加帐户功能

**Comment by uhziel** [comment]
如果只存配置文件，在做简单的应用时确实会很简单方便。但如果这样，就变成了单用户应用。
而后续想添加账号系统变成多用户应用，数据的组织和使用会产生很多变化，改造代码的成本会很高。

这个账号系统已经快开发完，后续再扩展其他功能就会方便很多了。
部署上确实会变得麻烦点，因为多个数据库依赖，到时候会给个使用 docker-compose 的例子进行部署，也不会麻烦太多。

**Comment by db-one** [comment]
嗯  谢谢 期待下一个大更新版本

**Comment by db-one** [comment]
- MONGODB_URI=mongodb://root:pZXswnYF#ch6iU@db:27017/yireader?authSource=admin&retryWrites=true&w=majority

这里支持mysql数据库吗，已经有现成的mysqld容器了，可以直接连接上去

**Comment by uhziel** [comment]
并没有使用 mysql ，使用的是 mongodb，它在 nodejs 环境中使用会更方便些。

我还没有发布正式版，还在内部测试处理其中遇到的问题。

如果你想体验的话，可以体验预发布版，文档我整理在 [使用 docker-compose 进行部署](https://uhziel.github.io/yireader/user/deploy.html#%E4%BD%BF%E7%94%A8-docker-compose-%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2)

**Comment by uhziel** [comment]
已经发布正式版 v0.3.0，欢迎使用和提供建议

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/111030512-999ce580-843d-11eb-9eb6-10913544ccbf.png)
已经部署成功了，不过我是这样部署的
个人不太喜欢docker-compose的方法，这样数据库等于独立出来了，以后有别的容器有需要也可以直接接入
使用默认没有自带的源了，按照上面的方法找了几个源，都不太好用，其他倒是都挺好的，我自己是部署在家庭服务器上自己用的，要是可以支持免注册，直接看就更好了，顺便还能保存进度这样，比如加一个系统默认的帐户，把数据一样存入到数据库，非注册状态就调用默认帐户来存储进度

**Comment by uhziel** [comment]
1 docker-compose 方式也可以独立出数据库，你把它拆成两个就行，再就是把 db 的 ports 也映射出来。docker-compose 的好处主要是方便后续升级新版本，docker-compose pull && docker-compose up -d 一键完成。当然，这个就是个人偏好了，你动手能力还是挺强的。
2 书源这个问题请自行解决啦~
3 免注册这个是存在风险的。因为别人能不登录就往你的数据库写数据。而且，只是共用一个默认账户的话，互联网上任何人都可以看到你的个人数据了。
